# ❤Numpy❤

### 0.Basics

In [2]:
import numpy as np

In [2]:
np.array([2,3]).dtype

dtype('int32')

In [3]:
#onedimension_array
arr1=np.array([1,2,3])
arr1

array([1, 2, 3])

In [4]:
#twodimension_array
arr2=np.array([[1,2],[3,4]],dtype="int8")
arr2

array([[1, 2],
       [3, 4]], dtype=int8)

In [5]:
#dimension
print(arr1.ndim)
print(arr2.ndim)


1
2


In [6]:
#type
print(type(arr1))

<class 'numpy.ndarray'>


In [7]:
#num_of elements
print(arr1.size)
print(arr2.size)

3
4


In [8]:
#shape of array
print(arr1.shape)
print(arr2.shape)

(3,)
(2, 2)


In [9]:
#total_memory_taken
print(arr1.nbytes)
print(arr2.nbytes)

12
4


In [10]:
print(arr1.dtype)
print(arr2.dtype)

int32
int8


### 1.Arange

In [11]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(1,10,3)

array([1, 4, 7])

In [14]:
print(np.arange(1,10,2,dtype="float"))
print(np.arange(1,10,3,dtype='int'))
print(np.arange(1,10,3,dtype='complex'))

[1. 3. 5. 7. 9.]
[1 4 7]
[1.+0.j 4.+0.j 7.+0.j]


### 1.Zeros

In [15]:
zero=np.zeros(4)
zero1=np.zeros((4,4),dtype="complex")
zero2=np.zeros((4,4,4))
print(zero)
print("second dimension")
print(zero1)
print("third dimension")
print(zero2)

[0. 0. 0. 0.]
second dimension
[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]
third dimension
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


### 2.Ones

In [16]:
one=np.ones(4)
one1=np.ones((3,3),dtype=complex)
one2=np.ones((3,3,3))
print(one)
print("second dimension")
print(one1)
print("three dimension")
print(one2)
one2[1,1,1]

[1. 1. 1. 1.]
second dimension
[[1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]]
three dimension
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


1.0

### 3.Identity

In [17]:
identity=np.eye(3,2)
identity1=np.eye(2,2)
print(identity)
print()
print(identity1)

[[1. 0.]
 [0. 1.]
 [0. 0.]]

[[1. 0.]
 [0. 1.]]


In [18]:
idn=np.identity(3)
print(idn)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 4.Array_Slicing

In [5]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[3:7])

[4 5 6 7]


In [3]:
arr=np.array([[9,8,7],[0,1,2]])
print(arr[0,0])

9


In [21]:
arr=np.array([[[1,9,0,3,5],[2,4,8,2,1]],[[1,2,3,4,5],[5,6,4,2,1]]])
print(arr[1][1][2:])

[4 2 1]


In [22]:
#where_function
np.where(arr<3,arr,"f")

array([[['1', 'f', '0', 'f', 'f'],
        ['2', 'f', 'f', '2', '1']],

       [['1', '2', 'f', 'f', 'f'],
        ['f', 'f', 'f', '2', '1']]], dtype='<U11')

In [23]:
#logical_and
np.logical_and(arr>3,arr<=5)

array([[[False, False, False, False,  True],
        [False,  True, False, False, False]],

       [[False, False, False,  True,  True],
        [ True, False,  True, False, False]]])

### 5.Copy

In [24]:
arr2
arr3=arr2.copy()
arr3[0][0]=10
print(arr3)

[[10  2]
 [ 3  4]]


In [25]:
arr2

array([[1, 2],
       [3, 4]], dtype=int8)

In [26]:
arr
arr3d=arr.copy()
print(arr3d)
arr3d[1][1][3]

[[[1 9 0 3 5]
  [2 4 8 2 1]]

 [[1 2 3 4 5]
  [5 6 4 2 1]]]


2

### 6.Full

In [27]:
x=np.full((5,5),8)
print(x)

[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]


In [28]:
x=np.full((5,8),9)
print(x)

[[9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9]]


In [29]:
x=np.full((100,100),10)
print(x)

[[10 10 10 ... 10 10 10]
 [10 10 10 ... 10 10 10]
 [10 10 10 ... 10 10 10]
 ...
 [10 10 10 ... 10 10 10]
 [10 10 10 ... 10 10 10]
 [10 10 10 ... 10 10 10]]


### 7.Random_number

In [30]:
x=np.random.rand(3,5)
print(x)

[[0.73765346 0.41745774 0.87970383 0.41985714 0.43659123]
 [0.18528537 0.29346853 0.55030635 0.4580417  0.19768559]
 [0.80146874 0.51931858 0.50334105 0.5333333  0.79915891]]


In [31]:
print(np.random.randint(2,6,size=(3,3)))
print()
print(np.random.randint(5,size=3))

[[2 3 4]
 [4 2 2]
 [3 2 5]]

[3 4 2]


In [32]:
np.random.ranf((3,3))

array([[0.07946994, 0.69766566, 0.81301769],
       [0.24698828, 0.65145488, 0.3275259 ],
       [0.96072337, 0.36102915, 0.83467365]])

### 8.Mathematical_Operation


In [33]:
ar=np.array([[1,2,3],[4,5,6]])
ar=ar+6
print(ar)


[[ 7  8  9]
 [10 11 12]]


In [34]:
ar=np.array([[1,2,3],[4,5,6]])
ar=ar-6
print(ar)

[[-5 -4 -3]
 [-2 -1  0]]


In [35]:
ar=np.array([[1,2,3],[4,5,6]])
ar=ar*6
print(ar)

[[ 6 12 18]
 [24 30 36]]


In [36]:
ar=np.array([[1,2,3],[4,5,6]])
ar=ar/6
print(ar)

[[0.16666667 0.33333333 0.5       ]
 [0.66666667 0.83333333 1.        ]]


### 9.Sin&Cos_Function

In [37]:
cos=np.cos(arr3)
print(cos)
print()
sin=np.sin(arr3)
print(sin)

[[-0.839  -0.4163]
 [-0.99   -0.654 ]]

[[-0.544   0.909 ]
 [ 0.1411 -0.757 ]]


### 10.Maximum_Minimum

In [38]:
mn=np.min(arr3)
print(mn)

2


In [39]:
mn=np.mean(arr3)
print(mn)

4.75


In [40]:
arr3.min()

2

In [41]:
mx=np.max(arr3)
print(mx)

10


### 11.Linspace

In [42]:
print(np.linspace(1,5,5))
print(np.linspace(1,2,5))
print(np.linspace(1,5,12,dtype="int"))

[1. 2. 3. 4. 5.]
[1.   1.25 1.5  1.75 2.  ]
[1 1 1 2 2 2 3 3 3 4 4 5]


### 12.Broadcasting

In [43]:
a=np.array([1,2,3,4])
b=np.array([[1,2,3,4],[1,4,5,6]])
a+b
#1.take 1 to the fewer dimension at the left side
#2one of the dimension should 1
#3compare the right side of dimension(must be match up)
#if 1,2,3 satisfied then the broadcasting applied

array([[ 2,  4,  6,  8],
       [ 2,  6,  8, 10]])

### 13.Flatten & Ravel

In [44]:
#flatten
b=np.array([[1,2,3,4],[1,4,5,6]])
x=b.flatten()#row_wise
b[0,0]=18
print(b)
print(x)


[[18  2  3  4]
 [ 1  4  5  6]]
[1 2 3 4 1 4 5 6]


In [45]:
#flatten
b=np.array([[1,2,3,4],[1,4,5,6]])
b.flatten(order="f")#column_wise

array([1, 1, 2, 4, 3, 5, 4, 6])

In [46]:
#ravel
b=np.array([[1,2,3,4],[1,4,5,6]])
x=np.ravel(b)#row_wise
print(x)

[1 2 3 4 1 4 5 6]


In [47]:
b[0,0]=18
print(b)
print(x)

[[18  2  3  4]
 [ 1  4  5  6]]
[18  2  3  4  1  4  5  6]


In [48]:
#ravel
b=np.array([[1,2,3,4],[1,4,5,6]])
np.ravel(b,order="F")#column_wise

array([1, 1, 2, 4, 3, 5, 4, 6])

### 14.Transpose & Swapaxes

In [49]:
print(arr3d)
arr3d.transpose()

[[[1 9 0 3 5]
  [2 4 8 2 1]]

 [[1 2 3 4 5]
  [5 6 4 2 1]]]


array([[[1, 1],
        [2, 5]],

       [[9, 2],
        [4, 6]],

       [[0, 3],
        [8, 4]],

       [[3, 4],
        [2, 2]],

       [[5, 5],
        [1, 1]]])

In [50]:
print((arr3d).shape)
np.transpose(arr3d).shape

(2, 2, 5)


(5, 2, 2)

In [51]:
print(a)
print(a.transpose())

[1 2 3 4]
[1 2 3 4]


### 15.Iteration

In [52]:
#one_dimension
for i in arr1:
    print(i)

1
2
3


In [53]:
#two_dimension
for i in arr3:
    for j in i:
        print(j)

10
2
3
4


### 16.Linear Algebra

In [54]:
a=np.ones((1,3))
b=np.full((3,2),2)
(np.matmul(a,b))

array([[6., 6.]])

In [55]:
b=np.identity(3)
print("The determinant:",np.linalg.det(b))

The determinant: 1.0


In [56]:
type((arr3))

numpy.ndarray

### 17.Reorganising Array

#### 1.reshape

In [57]:
a=np.ones((2,4))
print(a)
print("After reshaping:")
print(a.reshape((2,2,2)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
After reshaping:
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [58]:
b=np.reshape(a,(2,2,2))
b

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [59]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
np.reshape(a,(5,2))


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [60]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### 2.resize

In [61]:
x=np.array([1,2,3,4,5])
np.resize(x,(7,2))

array([[1, 2],
       [3, 4],
       [5, 1],
       [2, 3],
       [4, 5],
       [1, 2],
       [3, 4]])

#### 3.Stacking

In [62]:
#verticaly stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([8,3,4,2])
np.vstack((v1,v2))

array([[1, 2, 3, 4],
       [8, 3, 4, 2]])

In [63]:
#horizontal stacking vectors
h1=np.array([1,2,3,4])
h2=np.array([8,3,4,2])
np.hstack((h1,h2))

array([1, 2, 3, 4, 8, 3, 4, 2])

### 18.Load Data From File

In [64]:
file=np.genfromtxt('numpy.txt')
file.astype('int8')#"int8" or int


array([[ 1,  2,  3,  4,  5,  6,  7,  7,  8],
       [ 1,  2,  3,  4,  5,  6,  8,  3,  5],
       [ 1,  2,  3, 12,  3,  4,  5,  6,  7]], dtype=int8)

In [65]:
file>4

array([[False, False, False, False,  True,  True,  True,  True,  True],
       [False, False, False, False,  True,  True,  True, False,  True],
       [False, False, False,  True, False, False,  True,  True,  True]])

In [66]:
file[file<4]

array([1., 2., 3., 1., 2., 3., 3., 1., 2., 3., 3.])

In [67]:
file[file>4]

array([ 5.,  6.,  7.,  7.,  8.,  5.,  6.,  8.,  5., 12.,  5.,  6.,  7.])

In [68]:
np.any(file>7,axis=0)

array([False, False, False,  True, False, False,  True, False,  True])

In [69]:
np.any(file>7,axis=1)

array([ True,  True,  True])

In [70]:
ex=np.array([[1,2,3,4,5],
                  [6,7,8,9,10],
                   [11,12,13,14,15],
                   [16,17,18,19,20],
                 [21,22,23,24,25],
                 [26,27,28,29,30]])
ex

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [71]:
print(ex[2,0])
print(ex[2,1])
print(ex[3,0])
print(ex[3,1])
matrix=np.array([ex[2,0],ex[2,1],ex[3,0],ex[3,1]])
matrix

11
12
16
17


array([11, 12, 16, 17])

In [72]:
print(ex[2:4,0:2])
print()
print(ex[[0,1,2,3],[1,2,3,4]])
print()
print(ex[[0,4,5],3:])

[[11 12]
 [16 17]]

[ 2  8 14 20]

[[ 4  5]
 [24 25]
 [29 30]]


In [73]:
ex[:,-3:-1]

array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19],
       [23, 24],
       [28, 29]])

In [74]:

arr3d

array([[[1, 9, 0, 3, 5],
        [2, 4, 8, 2, 1]],

       [[1, 2, 3, 4, 5],
        [5, 6, 4, 2, 1]]])

In [76]:
arr3

array([[10,  2],
       [ 3,  4]], dtype=int8)

In [77]:
arr2

array([[1, 2],
       [3, 4]], dtype=int8)

In [79]:
np.concatenate((arr3,arr2))

array([[10,  2],
       [ 3,  4],
       [ 1,  2],
       [ 3,  4]], dtype=int8)